aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "yarn-lock.json" }}-v1.0

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "yarn-lock.json" }}-v1.0

version: 2
jobs:
  checkout:
    docker: 
      - image: node:10.5.0
    working_directory: ~/record-union
    steps:
      - checkout
      - run: yarn install

  unit-test:
    - checkout
    - run: yarn test

  build:
    steps:
      - checkout
      - run: yarn build
      - deploy:

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master