const FETCH_STATUS = {
  FETCH_STARTED: 'FETCH_STARTED',
  FETCH_DONE: 'FETCH_DONE',
  FETCH_EMPTY: 'FETCH_EMPTY',
  FETCH_ERROR: 'FETCH_ERROR'
}

const ADD_STATUS = {
  ADD_STARTED: 'ADD_STARTED',
  ADD_DONE: 'ADD_DONE',
  ADD_ERROR: 'ADD_ERROR'
}

const REMOVE_STATUS = {
  REMOVE_STARTED: 'REMOVE_STARTED',
  REMOVE_DONE: 'REMOVE_DONE',
  REMOVE_ERROR: 'REMOVE_ERROR'
}

const UPDATE_STATUS = {
  UPDATE_STARTED: 'UPDATE_STARTED',
  UPDATE_DONE: 'UPDATE_DONE'
}

export {
  FETCH_STATUS,
  ADD_STATUS,
  REMOVE_STATUS,
  UPDATE_STATUS
}