const FETCH_LIST_STARTED = 'FETCH_LIST_STARTED'
const FETCH_LIST_DONE = 'FETCH_LIST_DONE'
const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR'

const LIST_UPDATE_STARTED = 'LIST_UPDATE_STARTED'
const LIST_UPDATE_DONE = 'LIST_UPDATE_DONE'
const LIST_UPDATE_ERROR = 'LIST_UPDATE_ERROR'

const ADD_NOTE_STARTED = 'ADD_NOTE_STARTED'
const ADD_NOTE_DONE = 'ADD_NOTE_DONE'
const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR'

export {
  FETCH_LIST_STARTED,
  FETCH_LIST_DONE,
  FETCH_LIST_ERROR,
  LIST_UPDATE_STARTED,
  LIST_UPDATE_DONE,
  LIST_UPDATE_ERROR,
  ADD_NOTE_STARTED,
  ADD_NOTE_DONE,
  ADD_NOTE_ERROR
}