const FETCH_LIST_STARTED = 'FETCH_LIST_STARTED'
const FETCH_LIST_DONE = 'FETCH_LIST_DONE'
const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR'
const FETCH_LIST_DONE_EMPTY = 'FETCH_LIST_DONE_EMPTY'
const ADD_NOTE_STARTED = 'ADD_NOTE_STARTED'
const ADD_NOTE_DONE = 'ADD_NOTE_DONE'
const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR'

const REMOVE_NOTE_STARTED = 'REMOVE_NOTE_STARTED'
const REMOVE_NOTE_DONE = 'REMOVE_NOTE_DONE'
const REMOVE_NOTE_ERROR = 'REMOVE_NOTE_ERROR'

const FETCH_STATUS = {
  FETCH_STARTED: 'FETCH_STARTED',
  FETCH_DONE: 'FETCH_DONE',
  FETCH_EMPTY: 'FETCH_EMPTY',
  FETCH_ERROR: 'FETCH_ERROR'
}

const ADD_STATUS = {
  ADD_STARTED: 'ADD_STARTED',
  ADD_DONE: 'ADD_DONE',
  ADD_ERROR: 'ADD_ERROR'
}

const REMOVE_STATUS = {
  REMOVE_STARTED: 'REMOVE_STARTED',
  REMOVE_DONE: 'REMOVE_DONE',
  REMOVE_ERROR: 'REMOVE_ERROR'
}

export {
  FETCH_STATUS,
  ADD_STATUS,
  REMOVE_STATUS
}