machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  node:
    version: node:10.5.0

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
  pre:
    - yarn global add now

test:
  override:
    - yarn test

deployment:
  deploy:
    branch: master
    commands:
      - now -t ${ZEIT_TOKEN}