defaults: &defaults
    docker:
        - image: circleci/node:10.5.0
    working_directory: ~/record-union

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - yarn-cache-{{ .Branch }}
                    - yarn-cache-
            - run:
                name: YARN Install
                command: yarn install
            - save_cache:
                key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
    unit-test:
        <<: *defaults
        steps:
            - run:
                name: Unit Test
                command: yarn test
workflows:
    version: 2
    test:
        jobs:
            - checkout
            - unit-test:
                requires:
                    - checkout