defaults: &defaults
    docker:
        - image: circleci/node:10.5.0
    working_directory: ~/.

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - yarn-cache-{{ .Branch }}
                    - yarn-cache-
            - run:
                name: YARN Install
                command: yarn install
            - save_cache:
                key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
    unit-test:
        <<: *defaults
        steps:
            - run:
                name: Unit Test
                command: yarn install
            - run:
                command: yarn test
    deploy:
        <<: *defaults
        steps:
            - run:
                name: Install Now CLI
                command: sudo yarn install --global --unsafe-perm now
            - deploy:
                name: Deploy
                command: now -t ${ZEIT_TOKEN}
workflows:
    version: 2
    deploy:
        jobs:
            - checkout
            - unit-test
            - deploy:
                requires:
                    - unit-test