defaults: &defaults
    docker:
        - image: circleci/node:10.5.0
    working_directory: ~/record-union

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - yarn-cache-{{ .Branch }}
                    - yarn-cache-
            - run:
                name: YARN Install
                command: yarn install
            - save_cache:
                key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
    unit-test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Unit Test
                command: yarn add coveralls && yarn install
            - run:
                command: yarn test
            - run:
                command: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
    deploy:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Install Now CLI
                command: yarn install --g now
            - deploy:
                name: Deploy
                command: now -t ${ZEIT_TOKEN}
workflows:
    version: 2
    deploy:
        jobs:
            - checkout
            - unit-test:
                requires:
                    - checkout
            - deploy:
                requires:
                    - unit-test