aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "yarn-lock.json" }}-v1.0

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "yarn-lock.json" }}-v1.0

version: 2
jobs:
  checkout:
    docker: 
      - image: node:10.5.0
    working_directory: ~/record-union
    steps:
      - checkout
      - run: yarn install

  unit-test:
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run:
          name: Unit Test

  deploy:
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run:
          name: Install Now CLI
          command: sudo yarn install --global --unsafe-perm now
      - run:
          name: Deploy
          command: now --token $ZEIT_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout
      - unit-test:
          requires:
            - checkout
      - deploy:
          requires:
            - unit-test
          filters:
            branches:
              only: master